spring:
  #RabbitMQ配置
  rabbitmq:
    addresses: ${SHKB_RABBITMQ_ADDRESSES:127.0.0.1:5672} # RabbitMQ集群地址列表，多个地址用逗号分隔
    virtual-host: ${SHKB_RABBITMQ_VHOST:/}
    username: ${SHKB_RABBITMQ_USERNAME}
    password: ${SHKB_RABBITMQ_PASSWORD}
    connection-timeout: 60000 # 连接超时时间（毫秒），默认为60000毫秒（60秒）
    ssl:
      enabled: false       # 是否启用SSL，默认为false
      algorithm: TLSv1.2   # SSL算法，默认为TLSv1.2
    publisher-confirm-type: CORRELATED # Outbox 逐条关联发布确认
    publisher-returns: true  # 是否开启发布返回机制，默认为false
    listener:
      type: direct
      simple:
        acknowledge-mode: AUTO # 消费者确认模式，默认为auto
        retry:
          enabled: false       # 是否启用重试机制，默认为false
      direct:
        acknowledge-mode: AUTO # 消费者确认模式，默认为auto
        retry:
          enabled: false       # 是否启用重试机制，默认为false
