-- SHKB 人事、培训与人员授权核心 schema。
--
-- 本迁移依据 2026-08-16 对已部署产品的只读功能与 schema 核对建立：不写入
-- 业务数据，不删除或重建任何已有表。CREATE TABLE IF NOT EXISTS 使其可安全用于
-- 缺失 HR 表的现有租户库；已经具备这些表的生产库保持不变。
--
-- 注意：现网备份中已验证前 12 张表；人员授权附件实体已在部署代码中存在但备份
-- 未见对应表，因此在此作为缺失结构补齐，保持与本地 API 的附件能力一致。

CREATE TABLE IF NOT EXISTS `shkb_employee` (
  `id` varchar(32) NOT NULL COMMENT 'ID',
  `code` varchar(20) NOT NULL COMMENT '员工工号',
  `name` varchar(50) NOT NULL COMMENT '姓名',
  `gender` tinyint NOT NULL DEFAULT 0 COMMENT '性别：0-未知 1-男 2-女',
  `id_card` varchar(18) DEFAULT NULL COMMENT '身份证号',
  `birthday` date DEFAULT NULL COMMENT '出生日期',
  `nation` varchar(20) DEFAULT NULL COMMENT '民族',
  `native_place` varchar(100) DEFAULT NULL COMMENT '籍贯',
  `political_status` varchar(20) DEFAULT NULL COMMENT '政治面貌',
  `education` varchar(20) DEFAULT NULL COMMENT '学历',
  `major` varchar(50) DEFAULT NULL COMMENT '专业',
  `graduate_school` varchar(100) DEFAULT NULL COMMENT '毕业院校',
  `graduate_date` date DEFAULT NULL COMMENT '毕业日期',
  `phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `email` varchar(100) DEFAULT NULL COMMENT '电子邮箱',
  `address` varchar(200) DEFAULT NULL COMMENT '现居住地址',
  `emergency_contact` varchar(50) DEFAULT NULL COMMENT '紧急联系人',
  `emergency_phone` varchar(20) DEFAULT NULL COMMENT '紧急联系电话',
  `dept_id` varchar(32) DEFAULT NULL COMMENT '部门ID',
  `position` varchar(50) DEFAULT NULL COMMENT '职位',
  `entry_date` date DEFAULT NULL COMMENT '入职日期',
  `regular_date` date DEFAULT NULL COMMENT '转正日期',
  `leave_date` date DEFAULT NULL COMMENT '离职日期',
  `leave_reason` varchar(500) DEFAULT NULL COMMENT '离职原因',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：0-离职 1-在职 2-试用期',
  `photo_url` varchar(500) DEFAULT NULL COMMENT '照片URL',
  `description` varchar(500) DEFAULT '' COMMENT '备注',
  `create_by` varchar(32) NOT NULL COMMENT '创建人',
  `create_by_id` varchar(32) NOT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(32) NOT NULL COMMENT '修改人',
  `update_by_id` varchar(32) NOT NULL COMMENT '修改人ID',
  `update_time` datetime NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_shkb_employee_code` (`code`) USING BTREE,
  KEY `idx_shkb_employee_dept` (`dept_id`) USING BTREE,
  KEY `idx_shkb_employee_name` (`name`) USING BTREE,
  KEY `idx_shkb_employee_status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='员工基本信息表';

CREATE TABLE IF NOT EXISTS `shkb_employee_certificate` (
  `id` varchar(32) NOT NULL COMMENT 'ID',
  `employee_id` varchar(32) NOT NULL COMMENT '员工ID',
  `certificate_type` varchar(50) NOT NULL COMMENT '证书类型',
  `certificate_name` varchar(100) NOT NULL COMMENT '证书名称',
  `certificate_no` varchar(50) DEFAULT NULL COMMENT '证书编号',
  `issue_org` varchar(100) DEFAULT NULL COMMENT '发证机构',
  `issue_date` date DEFAULT NULL COMMENT '发证日期',
  `valid_start_date` date DEFAULT NULL COMMENT '有效期开始',
  `valid_end_date` date DEFAULT NULL COMMENT '有效期结束',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：0-过期 1-有效',
  `file_url` varchar(500) DEFAULT NULL COMMENT '证书扫描件URL',
  `description` varchar(500) DEFAULT '' COMMENT '备注',
  `create_by` varchar(32) NOT NULL COMMENT '创建人',
  `create_by_id` varchar(32) NOT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(32) NOT NULL COMMENT '修改人',
  `update_by_id` varchar(32) NOT NULL COMMENT '修改人ID',
  `update_time` datetime NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_shkb_employee_certificate_employee` (`employee_id`) USING BTREE,
  KEY `idx_shkb_employee_certificate_status` (`status`) USING BTREE,
  KEY `idx_shkb_employee_certificate_end` (`valid_end_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='员工证书表';

CREATE TABLE IF NOT EXISTS `shkb_employee_file` (
  `id` varchar(32) NOT NULL COMMENT 'ID',
  `employee_id` varchar(32) NOT NULL COMMENT '员工ID',
  `file_name` varchar(200) NOT NULL COMMENT '文件名称',
  `file_type` varchar(50) DEFAULT NULL COMMENT '文件类型',
  `file_url` varchar(500) NOT NULL COMMENT '文件URL',
  `file_size` bigint DEFAULT NULL COMMENT '文件大小（字节）',
  `description` varchar(500) DEFAULT '' COMMENT '备注',
  `create_by` varchar(32) NOT NULL COMMENT '创建人',
  `create_by_id` varchar(32) NOT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_shkb_employee_file_employee` (`employee_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='员工附件表';

CREATE TABLE IF NOT EXISTS `shkb_employee_training` (
  `id` varchar(32) NOT NULL COMMENT 'ID',
  `employee_id` varchar(32) NOT NULL COMMENT '员工ID',
  `training_name` varchar(100) NOT NULL COMMENT '培训名称',
  `training_type` varchar(50) DEFAULT NULL COMMENT '培训类型',
  `training_org` varchar(100) DEFAULT NULL COMMENT '培训机构',
  `training_content` text COMMENT '培训内容',
  `start_date` date DEFAULT NULL COMMENT '培训开始日期',
  `end_date` date DEFAULT NULL COMMENT '培训结束日期',
  `training_hours` decimal(10,1) DEFAULT NULL COMMENT '培训学时',
  `training_result` varchar(50) DEFAULT NULL COMMENT '培训结果',
  `certificate_no` varchar(50) DEFAULT NULL COMMENT '培训证书编号',
  `file_url` varchar(500) DEFAULT NULL COMMENT '培训证书扫描件URL',
  `description` varchar(500) DEFAULT '' COMMENT '备注',
  `create_by` varchar(32) NOT NULL COMMENT '创建人',
  `create_by_id` varchar(32) NOT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(32) NOT NULL COMMENT '修改人',
  `update_by_id` varchar(32) NOT NULL COMMENT '修改人ID',
  `update_time` datetime NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_shkb_employee_training_employee` (`employee_id`) USING BTREE,
  KEY `idx_shkb_employee_training_start` (`start_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='员工培训记录表';

CREATE TABLE IF NOT EXISTS `shkb_training_course` (
  `id` varchar(32) NOT NULL COMMENT 'ID',
  `tenant_id` varchar(32) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `course_name` varchar(100) NOT NULL COMMENT '课程名称',
  `course_type` varchar(50) DEFAULT NULL COMMENT '课程类型',
  `training_hours` decimal(10,1) DEFAULT NULL COMMENT '培训学时',
  `implementation_interval` int DEFAULT NULL COMMENT '实施间隔数值',
  `interval_unit` varchar(20) DEFAULT 'month' COMMENT '间隔单位：month-月 year-年',
  `description` text COMMENT '课程描述',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：0-禁用 1-启用',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_by_id` varchar(32) NOT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '修改人',
  `update_by_id` varchar(32) NOT NULL COMMENT '修改人ID',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志：0-正常 1-已删除',
  `initial_training_time` datetime DEFAULT NULL COMMENT '初训时间',
  `retraining_time` datetime DEFAULT NULL COMMENT '复训时间',
  `initial_training_hours` int DEFAULT NULL COMMENT '初训时长',
  `retraining_hours` int DEFAULT NULL COMMENT '复训时长',
  `teaching_method` varchar(100) DEFAULT NULL COMMENT '教学方式',
  `participants` varchar(100) DEFAULT NULL COMMENT '参训人员',
  `instructor` varchar(100) DEFAULT NULL COMMENT '教员',
  `training_outline` varchar(500) DEFAULT NULL COMMENT '培训提纲',
  `assessment_method` varchar(100) DEFAULT NULL COMMENT '考核方式',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_shkb_training_course_status` (`status`) USING BTREE,
  KEY `idx_shkb_training_course_tenant` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='培训课程表';

CREATE TABLE IF NOT EXISTS `shkb_training_course_file` (
  `id` varchar(32) NOT NULL COMMENT 'ID',
  `tenant_id` varchar(32) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `course_id` varchar(32) NOT NULL COMMENT '课程ID',
  `file_name` varchar(200) NOT NULL COMMENT '文件名称',
  `file_type` varchar(50) DEFAULT NULL COMMENT '文件类型',
  `file_url` varchar(500) NOT NULL COMMENT '文件URL',
  `file_size` bigint DEFAULT NULL COMMENT '文件大小（字节）',
  `description` varchar(500) DEFAULT NULL COMMENT '文件描述',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_by_id` varchar(32) NOT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志：0-正常 1-已删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_shkb_training_course_file_course` (`course_id`) USING BTREE,
  KEY `idx_shkb_training_course_file_tenant` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='培训课程文档表';

CREATE TABLE IF NOT EXISTS `shkb_training_implementation` (
  `id` varchar(32) NOT NULL COMMENT 'ID',
  `tenant_id` varchar(32) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `course_id` varchar(32) NOT NULL COMMENT '课程ID',
  `plan_start_date` date NOT NULL COMMENT '计划开始日期',
  `plan_end_date` date NOT NULL COMMENT '计划结束日期',
  `actual_start_date` datetime DEFAULT NULL COMMENT '实际开始时间',
  `actual_end_date` datetime DEFAULT NULL COMMENT '实际结束时间',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0-计划中 1-进行中 2-已完成 3-已取消',
  `training_location` varchar(200) DEFAULT NULL COMMENT '培训地点',
  `instructor` varchar(100) DEFAULT NULL COMMENT '培训讲师',
  `participant_count` int DEFAULT 0 COMMENT '学员人数',
  `description` text COMMENT '培训说明',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_by_id` varchar(32) NOT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '修改人',
  `update_by_id` varchar(32) NOT NULL COMMENT '修改人ID',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志：0-正常 1-已删除',
  `url` longtext COMMENT '附件URL',
  `file_name` varchar(100) DEFAULT NULL COMMENT '文件名称',
  `content_type` varchar(200) DEFAULT NULL COMMENT 'ContentType',
  `file_size` varchar(200) DEFAULT NULL COMMENT '文件大小',
  `file_suffix` varchar(200) DEFAULT NULL COMMENT '文件后缀',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_shkb_training_implementation_course` (`course_id`) USING BTREE,
  KEY `idx_shkb_training_implementation_status` (`status`) USING BTREE,
  KEY `idx_shkb_training_implementation_tenant` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='培训实施计划表';

CREATE TABLE IF NOT EXISTS `shkb_training_participant` (
  `id` varchar(32) NOT NULL COMMENT 'ID',
  `tenant_id` varchar(32) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `implementation_id` varchar(32) NOT NULL COMMENT '实施计划ID',
  `employee_id` varchar(32) NOT NULL COMMENT '员工ID',
  `training_result` varchar(20) DEFAULT '待定' COMMENT '培训结果：合格/优秀/不合格/待定',
  `certificate_no` varchar(100) DEFAULT NULL COMMENT '证书编号',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：0-未开始 1-进行中 2-已完成',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_by_id` varchar(32) NOT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '修改人',
  `update_by_id` varchar(32) NOT NULL COMMENT '修改人ID',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志：0-正常 1-已删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_shkb_training_participant_impl_employee` (`implementation_id`, `employee_id`) USING BTREE,
  KEY `idx_shkb_training_participant_employee` (`employee_id`) USING BTREE,
  KEY `idx_shkb_training_participant_implementation` (`implementation_id`) USING BTREE,
  KEY `idx_shkb_training_participant_tenant` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='培训学员表';

CREATE TABLE IF NOT EXISTS `shkb_authorization_project` (
  `id` varchar(32) NOT NULL COMMENT 'ID',
  `tenant_id` varchar(32) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `project_name` varchar(100) NOT NULL COMMENT '项目名称',
  `project_type` varchar(50) DEFAULT NULL COMMENT '项目类型',
  `validity_period` int NOT NULL COMMENT '有效期数值',
  `validity_unit` varchar(20) NOT NULL DEFAULT 'month' COMMENT '有效期单位：month-月 year-年',
  `description` text COMMENT '项目描述',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：0-禁用 1-启用',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_by_id` varchar(32) NOT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '修改人',
  `update_by_id` varchar(32) NOT NULL COMMENT '修改人ID',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志：0-正常 1-已删除',
  `authorization_item` varchar(1024) DEFAULT NULL COMMENT '授权项目/限制',
  `qualification_requirement` varchar(500) DEFAULT NULL COMMENT '资质要求',
  `training_requirement` varchar(200) DEFAULT NULL COMMENT '培训要求',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_shkb_authorization_project_status` (`status`) USING BTREE,
  KEY `idx_shkb_authorization_project_tenant` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='授权项目表';

CREATE TABLE IF NOT EXISTS `shkb_authorization_required_course` (
  `id` varchar(32) NOT NULL COMMENT 'ID',
  `tenant_id` varchar(32) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `project_id` varchar(32) NOT NULL COMMENT '授权项目ID',
  `course_id` varchar(32) NOT NULL COMMENT '课程ID',
  `is_required` tinyint NOT NULL DEFAULT 1 COMMENT '是否必修：0-选修 1-必修',
  `create_by` varchar(32) NOT NULL COMMENT '创建人',
  `create_by_id` varchar(32) NOT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志：0-正常 1-已删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_shkb_authorization_required_course` (`project_id`, `course_id`) USING BTREE,
  KEY `idx_shkb_authorization_required_course_course` (`course_id`) USING BTREE,
  KEY `idx_shkb_authorization_required_course_project` (`project_id`) USING BTREE,
  KEY `idx_shkb_authorization_required_course_tenant` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='授权项目必修课程关联表';

CREATE TABLE IF NOT EXISTS `shkb_person_authorization` (
  `id` varchar(32) NOT NULL COMMENT 'ID',
  `tenant_id` varchar(32) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `employee_id` varchar(32) NOT NULL COMMENT '员工ID',
  `authorization_date` date DEFAULT NULL COMMENT '授权日期',
  `expiry_date` date DEFAULT NULL COMMENT '到期日期',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：0-已过期 1-有效 2-即将过期 3-无效',
  `credential_file_url` varchar(500) DEFAULT NULL COMMENT '凭据附件URL',
  `credential_file_name` varchar(200) DEFAULT NULL COMMENT '凭据附件名称',
  `description` text COMMENT '备注',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_by_id` varchar(32) NOT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '修改人',
  `update_by_id` varchar(32) NOT NULL COMMENT '修改人ID',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志：0-正常 1-已删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_shkb_person_authorization_employee` (`employee_id`) USING BTREE,
  KEY `idx_shkb_person_authorization_expiry` (`expiry_date`) USING BTREE,
  KEY `idx_shkb_person_authorization_status` (`status`) USING BTREE,
  KEY `idx_shkb_person_authorization_tenant` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='人员授权主表';

CREATE TABLE IF NOT EXISTS `shkb_person_authorization_project` (
  `id` varchar(32) NOT NULL COMMENT 'ID',
  `tenant_id` varchar(32) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `authorization_id` varchar(32) NOT NULL COMMENT '授权主表ID',
  `project_id` varchar(32) NOT NULL COMMENT '授权项目ID',
  `authorization_date` date NOT NULL COMMENT '授权日期',
  `expiry_date` date NOT NULL COMMENT '到期日期',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：0-已过期 1-有效 2-即将过期 3-无效',
  `required_courses_completed` tinyint NOT NULL DEFAULT 0 COMMENT '必修课程是否完成：0-未完成 1-已完成',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_by_id` varchar(32) NOT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '修改人',
  `update_by_id` varchar(32) NOT NULL COMMENT '修改人ID',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志：0-正常 1-已删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_shkb_person_authorization_project` (`authorization_id`, `project_id`) USING BTREE,
  KEY `idx_shkb_person_authorization_project_authorization` (`authorization_id`) USING BTREE,
  KEY `idx_shkb_person_authorization_project_project` (`project_id`) USING BTREE,
  KEY `idx_shkb_person_authorization_project_tenant` (`tenant_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='人员授权项目关联表';

CREATE TABLE IF NOT EXISTS `shkb_person_authorization_file` (
  `id` varchar(32) NOT NULL COMMENT 'ID',
  `authorization_id` varchar(32) NOT NULL COMMENT '人员授权ID',
  `file_name` varchar(200) NOT NULL COMMENT '文件名称',
  `file_type` varchar(50) DEFAULT NULL COMMENT '文件类型',
  `file_size` bigint DEFAULT NULL COMMENT '文件大小（字节）',
  `file_url` varchar(500) NOT NULL COMMENT '文件URL',
  `create_by` varchar(32) NOT NULL COMMENT '创建人',
  `create_by_id` varchar(32) NOT NULL COMMENT '创建人ID',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_shkb_person_authorization_file_authorization` (`authorization_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='人员授权附件表';
